version: '3.4'

services:
  catalogdb:
    image: mongo

  catalogo.api:
    image: ${DOCKER_REGISTRY-}catalogoapi
    build:
      context: .
      dockerfile: Catalogo.API/Dockerfile

volumes:
  mongo_data:
